---
version: "2.1"
services:
  code-server:
    image: lscr.io/linuxserver/code-server:latest
    container_name: code-server
    environment:
      - PUID=user_id
      - PGID=group_id
      - TZ=time_zone
      - PASSWORD=examplepass
      - SUDO_PASSWORD=examplepass #optional
    volumes:
      - /docker/code-server:/config
    ports:
      - 7443:8443
    restart: unless-stopped
