---
version: "2.1"
services:
  dillinger:
    image: lscr.io/linuxserver/dillinger:latest
    container_name: dillinger
    environment:
      - PUID=user_id
      - PGID=group_id
      - TZ=time_zone
    volumes:
      - /docker/dillinger:/config
    ports:
      - 8085:8080
    restart: always
