version: "3"
services:
  filebrowser:
    image: hurlenko/filebrowser
    ports:
      - 8083:8080
    volumes:
      - /:/data
      - /docker/filebrowser:/config
    environment:
      - PUID=user_id
      - PGID=group_id
      - TZ=time_zone
      - FB_BASEURL=/filebrowser
    restart: always
