version: '2.1'
services:
  trilium:
    build:
      context: .
    image: zadam/trilium
    restart: always
    environment:
      - TRILIUM_DATA_DIR=/data
    ports:
      - "85:8080"
    volumes:
      - trilium:/data
      
volumes:
  trilium:
