version: "3"
services:
  plex:
    image: lscr.io/linuxserver/plex
    container_name: plex
    network_mode: host
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - VERSION=docker
    volumes:
      - ${CONFIG}plex:/config
      - ${TV}:/tv
      - ${MOVIES}:/movies
    restart: unless-stopped
