version: "3"
services:
  jackett:
    image: lscr.io/linuxserver/jackett
    container_name: jackett
    restart: unless-stopped
    environment:
      - PUID=user_id
      - PGID=group_id
      - TZ=time_zone
      - AUTO_UPDATE=true
    volumes:
      - /docker/jackett:/config
    ports:
      - 9117:9117
