version: "3"
services:
  plex:
    image: lscr.io/linuxserver/plex
    container_name: plex
    network_mode: host
    environment:
      - PUID=user_id
      - PGID=group_id
      - TZ=time_zone
      - VERSION=docker
    volumes:
      - /docker/plex:/config
      - path_for_series:/tv
      - path_for_movies:/movies
    restart: unless-stopped
