version: "3"
services:
  radarr:
    image: lscr.io/linuxserver/radarr
    container_name: radarr
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG}/radarr:/config
      - ${MOVIES}:/movies
      - ${DOWNLOADS}:/download
    ports:
      - 7878:7878
