version: "3"
services:
  radarr:
    image: lscr.io/linuxserver/radarr
    container_name: radarr
    restart: unless-stopped
    environment:
      - PUID=user_id
      - PGID=group_id
      - TZ=time_zone
    volumes:
      - /docker/radarr:/config
      - path_for_movies:/movies
      - path_for_down:/download
    ports:
      - 7878:7878
