version: "3"
services:
  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd
    container_name: sabnzbd
    restart: unless-stopped
    environment:
      - PUID=user_id
      - PGID=group_id
      - TZ=time_zone
    volumes:
      - /docker/sabnzdb:/config
      - path_for_down:/download
    ports:
      - 8080:8080
