version: "3"
services:
  sonarr:
    image: lscr.io/linuxserver/sonarr
    container_name: sonarr
    restart: unless-stopped
    environment:
      - PUID=user_id
      - PGID=group_id
      - TZ=time_zone
    volumes:
      - /docker/sonarr:/config
      - path_for_series:/tv
      - path_for_down:/download
    ports:
      - 8989:8989
