version: "3"
services:
  sonarr:
    image: lscr.io/linuxserver/sonarr
    container_name: sonarr
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}      
      - TZ=${TZ}
    volumes:
      - ${CONFIG}sonarr:/config
      - ${TV}
      - ${DOWNLOADS}
    ports:
      - 8989:8989
