version: "3"
services:
  tautulli:
    image: lscr.io/linuxserver/tautulli
    container_name: tautulli
    restart: unless-stopped
    environment:
      - PUID=user_id
      - PGID=group_id
      - TZ=time_zone
    volumes:
      - /docker/tautulli:/config
    ports:
      - 8181:8181
